version: "3"
services:
  db:
    image: "postgres"
    container_name: "localpg"
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: true